using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using Hellgate.Excel;
using Hellgate.Excel.TCv4;
using SkillEventTypes = Hellgate.Excel.SkillEventTypes;
using Stats = Hellgate.Excel.Stats;
using UnitModes = Hellgate.Excel.UnitModes;

namespace Hellgate
{
    public abstract class DataFile
    {
        // public abstract String StringId { get; protected set; }
        public String StringId { get; protected set; }
        public Type DataType { get; protected set; }
        public uint StructureId { get; protected set; }
        public bool HasIntegrity { get; protected set; }
        public bool IsExcelFile { get; protected set; }
        public bool IsStringsFile { get; protected set; }
        public int Count { get { return (Rows != null) ? Rows.Count : 0; } }
        public string FilePath { get; set; }
        public string FileExtension { get; set; }
        public string FileName { get { return Path.GetFileNameWithoutExtension(Path.GetFileNameWithoutExtension(FilePath)); } }
        public List<Object> Rows { get; protected set; }

        public override string ToString()
        {
            return StringId;
        }
        public abstract bool ParseData(byte[] buffer);
        public abstract bool ParseCSV(byte[] buffer);
        public abstract bool ParseDataTable(DataTable dataTable);
        public abstract byte[] ToByteArray();
        public abstract byte[] ExportCSV();

        public class MapEntry
        {
            public bool IsTCv4 { get; set; }
            public String FileName { get; set; }
            public Type RowType { get; set; }
            public bool IsEmpty { get; set; }
            public bool IsMythos { get; set; }
            public DataFile LoadedFile { get; set; }
            public bool ManualLoad { get; set; }
            public bool HasIndexBitRelations { get; set; }
            public bool HasScriptTable { get; set; }
            public bool HasExtended { get; set; }
        }

        protected static readonly Dictionary<String, MapEntry> DataTableMap = new Dictionary<String, MapEntry>
        {
            // Excel files
            {"ACHIEVEMENTS", new MapEntry {RowType = typeof(Achievements)}},
            {"ACT", new MapEntry {RowType = typeof(Act)}},
            {"AFFIXES", new MapEntry {RowType = typeof(Affixes)}},
            {"AFFIXTYPES", new MapEntry {RowType = typeof(AffixTypes)}},
            {"AI_BEHAVIOR", new MapEntry {RowType = typeof(AiBehaviour)}},
            {"AICOMMON_STATE", new MapEntry {RowType = typeof(AiCommonState)}},
            {"AI_INIT", new MapEntry {RowType = typeof(AiInit)}},
            {"AI_START", new MapEntry {RowType = typeof(AiStart)}},
            {"ANIMATION_CONDITION", new MapEntry {RowType = typeof(AnimationCondition)}},
            {"ANIMATION_GROUP", new MapEntry {FileName = "ANIMATION_GROUPS", RowType = typeof(AnimationGroups)}},
            {"ANIMATION_STANCE", new MapEntry {RowType = typeof(AnimationStance)}},
            {"BACKGROUNDSOUNDS", new MapEntry {RowType = typeof(BackGroundSounds)}},
            {"BACKGROUNDSOUNDS2D", new MapEntry {RowType = typeof(BackGroundSounds2D)}},
            {"BACKGROUNDSOUNDS3D", new MapEntry {RowType = typeof(BackGroundSounds3D)}},
            {"BADGE_REWARDS", new MapEntry {RowType = typeof(BadgeRewards)}},
            {"BONES", new MapEntry {RowType = typeof(Bones)}},
            {"BONEWEIGHTS", new MapEntry {RowType = typeof(Bones)}},
            {"BOOKMARKS", new MapEntry {RowType = typeof(ExcelTables)}},
            {"BUDGETS_MODEL", new MapEntry {RowType = typeof(BudgetsModel)}},
            {"BUDGETS_TEXTURE_MIPS", new MapEntry {RowType = typeof(BudgetTextureMips)}},
            {"CHAT_INSTANCED_CHANNELS", new MapEntry {RowType = typeof(ChatInstancedChannels)}},
            {"CHARACTER_CLASS", new MapEntry {RowType = typeof(CharacterClass)}},
            {"COLORSETS", new MapEntry {RowType = typeof(ColorSets)}},
            {"CONDITION_FUNCTIONS", new MapEntry {RowType = typeof(ConditionFunctions)}},
            {"DAMAGE_EFFECTS", new MapEntry {FileName = "DAMAGEEFFECTS", RowType = typeof(DamageEffects)}},
            {"DAMAGETYPES", new MapEntry {RowType = typeof(DamageTypes)}},
            {"DIALOG", new MapEntry {RowType = typeof(Dialog)}},
            {"DIFFICULTY", new MapEntry {RowType = typeof(Difficulty)}},
            {"CHARDISPLAY", new MapEntry {FileName = "DISPLAY_CHAR", RowType = typeof(Display)}},
            {"ITEMDISPLAY", new MapEntry {FileName = "DISPLAY_ITEM", RowType = typeof(Display)}},
            {"EFFECTS_FILES", new MapEntry {RowType = typeof(EffectsFiles)}},
            {"EFFECTS", new MapEntry {FileName = "EFFECTS_INDEX", RowType = typeof(EffectsIndex)}},
            {"EFFECTS_SHADERS", new MapEntry {RowType = typeof(EffectsShaders)}},
            {"EXCELTABLES", new MapEntry {RowType = typeof(ExcelTables)}},
            {"FACTION", new MapEntry {RowType = typeof(Faction)}},
            {"FACTION_STANDING", new MapEntry {RowType = typeof(FactionStanding)}},
            {"FILTER_CHATFILTER", new MapEntry {FileName = "CHATFILTER", RowType = typeof(Filter)}},
            {"FILTER_NAMEFILTER", new MapEntry {FileName = "NAMEFILTER", RowType = typeof(Filter)}},
            {"FONT", new MapEntry {RowType = typeof(Font)}},
            {"FONTCOLORS", new MapEntry {FileName = "FONTCOLOR", RowType = typeof(FontColor)}},
            {"FOOTSTEPS", new MapEntry {RowType = typeof(FootSteps)}},
            {"GAME_GLOBALS", new MapEntry {FileName = "GAMEGLOBALS", RowType = typeof(GameGlobals)}},
            {"GLOBAL_INDEX", new MapEntry {FileName = "GLOBALINDEX", RowType = typeof(Global)}},
            {"GLOBAL_STRING", new MapEntry {FileName = "GLOBALSTRING", RowType = typeof(Global)}},
            {"GLOBAL_THEMES", new MapEntry {RowType = typeof(GlobalThemes)}},
            {"INITDB", new MapEntry {RowType = typeof(InitDb)}},
            {"INTERACT", new MapEntry {RowType = typeof(Interact)}},
            {"INTERACT_MENU", new MapEntry {RowType = typeof(InteractMenu)}},
            {"INVENTORY", new MapEntry {RowType = typeof(Inventory)}},
            {"INVENTORY_TYPES", new MapEntry {RowType = typeof(InventoryTypes)}},
            {"INVLOC", new MapEntry {RowType = typeof(InvLoc)}},
            {"ITEM_LEVELS", new MapEntry {RowType = typeof(ItemLevels)}},
            {"ITEM_LOOK_GROUPS", new MapEntry {RowType = typeof(ItemLookGroups)}},
            {"ITEM_LOOKS", new MapEntry {RowType = typeof(ItemLooks)}},
            {"ITEM_QUALITY", new MapEntry {FileName = "ITEMQUALITY", RowType = typeof(ItemQuality)}},
            {"ITEMS", new MapEntry {RowType = typeof(Items), HasExtended = true}},
            {"LEVEL", new MapEntry {FileName = "LEVELS", RowType = typeof(Levels)}},
            {"LEVEL_DRLG_CHOICE", new MapEntry {FileName = "LEVELS_DRLG_CHOICE", RowType = typeof(LevelsDrlgChoice)}},
            {"LEVEL_DRLGS", new MapEntry {FileName = "LEVELS_DRLGS", RowType = typeof(LevelsDrlgs)}},
            {"LEVEL_FILE_PATHS", new MapEntry {FileName = "LEVELS_FILE_PATH", RowType = typeof(LevelsFilePath)}},
            {"LEVEL_ENVIRONMENTS", new MapEntry {FileName = "LEVELS_ENV", RowType = typeof(LevelsEnv)}},
            {"ROOM_INDEX", new MapEntry {FileName = "LEVELS_ROOM_INDEX", RowType = typeof(LevelsRoomIndex)}},
            {"LEVEL_RULES", new MapEntry {FileName = "LEVELS_RULES", RowType = typeof(LevelsRules)}},
            {"LEVEL_THEMES", new MapEntry {FileName = "LEVELS_THEMES", RowType = typeof(LevelsThemes)}},
            {"LEVEL_SCALING", new MapEntry {FileName = "LEVELSCALING", RowType = typeof(LevelScaling)}},
            {"LOADING_TIPS", new MapEntry {RowType = typeof(LoadingTips)}},
            {"MATERIALS_COLLISION", new MapEntry {RowType = typeof(MaterialsCollision)}},
            {"MATERIALS_GLOBAL", new MapEntry {RowType = typeof(MaterialsGlobal)}},
            {"MELEEWEAPONS", new MapEntry {RowType = typeof(MeleeWeapons)}},
            {"MISSILES", new MapEntry {RowType = typeof(Items), HasExtended = true}},
            {"MONLEVEL", new MapEntry {RowType = typeof(MonLevel)}},
            {"MONSCALING", new MapEntry {RowType = typeof(MonScaling)}},
            {"MONSTER_NAME_TYPES", new MapEntry {RowType = typeof(MonsterNameTypes)}},
            {"MONSTER_NAMES", new MapEntry {RowType = typeof(MonsterNames)}},
            {"MONSTER_QUALITY", new MapEntry {RowType = typeof(MonsterQuality)}},
            {"MONSTERS", new MapEntry {RowType = typeof(Items), HasExtended = true}},
            {"MOVIE_SUBTITLES", new MapEntry {RowType = typeof(MovieSubTitles)}},
            {"MOVIELISTS", new MapEntry {RowType = typeof(MovieLists)}},
            {"MOVIES", new MapEntry {RowType = typeof(Movies)}},
            {"MUSIC", new MapEntry {RowType = typeof(Music)}},
            {"MUSICCONDITIONS", new MapEntry {RowType = typeof(MusicConditions)}},
            {"MUSICGROOVELEVELS", new MapEntry {RowType = typeof(MusicGrooveLevels)}},
            {"MUSICGROOVELEVELTYPES", new MapEntry {RowType = typeof(MusicGrooveLevelTypes)}},
            {"MUSIC_REF", new MapEntry {FileName = "MUSICREF", RowType = typeof(MusicRef)}},
            {"MUSIC_SCRIPT_DEBUG", new MapEntry {FileName = "MUSICSCRIPTDEBUG", RowType = typeof(MusicScriptDebug)}},
            {"MUSICSTINGERS", new MapEntry {RowType = typeof(MusicStingers)}},
            {"MUSICSTINGERSETS", new MapEntry {RowType = typeof(MusicStingerSets)}},
            {"NPC", new MapEntry {RowType = typeof(Npc)}},
            {"OBJECTS", new MapEntry {RowType = typeof(Items), HasExtended = true}},
            {"OBJECTTRIGGERS", new MapEntry {RowType = typeof(ObjectTriggers)}},
            {"OFFER", new MapEntry {RowType = typeof(Offer)}},
            {"PALETTES", new MapEntry {RowType = typeof(Palettes)}},
            {"PETLEVEL", new MapEntry {RowType = typeof(MonLevel)}},
            {"PLAYERLEVELS", new MapEntry {RowType = typeof(PlayerLevels)}},
            {"PLAYER_RACE", new MapEntry {FileName = "PLAYERRACE", RowType = typeof(PlayerRace)}},
            {"PLAYERS", new MapEntry {RowType = typeof(Items), HasExtended = true}},
            {"PROPERTIES", new MapEntry {RowType = typeof(Properties), HasScriptTable = true}},
            {"PROCS", new MapEntry {RowType = typeof(Procs)}},
            {"PROPS", new MapEntry {RowType = typeof(LevelsRoomIndex)}},
            {"QUEST", new MapEntry {RowType = typeof(Quest)}},
            {"QUEST_CAST", new MapEntry {RowType = typeof(QuestCast)}},
            {"QUEST_STATE", new MapEntry {RowType = typeof(QuestState)}},
            {"QUEST_STATE_VALUE", new MapEntry {RowType = typeof(ExcelTables)}},
            {"QUEST_STATUS", new MapEntry {RowType = typeof(QuestStatus)}},
            {"QUEST_TEMPLATE", new MapEntry {RowType = typeof(QuestTemplate)}},
            {"RARENAMES", new MapEntry {RowType = typeof(RareNames)}},
            {"RECIPELISTS", new MapEntry {RowType = typeof(RecipeLists)}},
            {"RECIPES", new MapEntry {RowType = typeof(Recipes)}},
            {"SKILLGROUPS", new MapEntry {RowType = typeof(SkillGroups)}},
            {"SKILLS", new MapEntry {RowType = typeof(Skills), HasScriptTable = true}},
            {"SKILLEVENTTYPES", new MapEntry {RowType = typeof(SkillEventTypes)}},
            {"SKILLTABS", new MapEntry {RowType = typeof(SkillTabs)}},
            {"SKU", new MapEntry {RowType = typeof(Sku)}},
            {"SOUNDBUSES", new MapEntry {RowType = typeof(SoundBuses)}},
            {"SOUND_MIXSTATES", new MapEntry {FileName = "SOUNDMIXSTATES", RowType = typeof(SoundMixStates)}},
            {"SOUND_MIXSTATE_VALUES", new MapEntry {FileName = "SOUNDMIXSTATEVALUES", RowType = typeof(SoundMixStateValues)}},
            {"SOUNDS", new MapEntry {RowType = typeof(Sounds)}},
            {"SOUNDVCAS", new MapEntry {RowType = typeof(SoundVidCas)}},
            {"SOUNDVCASETS", new MapEntry {RowType = typeof(SoundVideoCasets)}},
            {"SPAWN_CLASS", new MapEntry {FileName = "SPAWNCLASS", RowType = typeof(SpawnClass)}},
            {"SUBLEVEL", new MapEntry {RowType = typeof(SubLevel)}},
            {"STATE_EVENT_TYPES", new MapEntry {RowType = typeof(StateEventTypes)}},
            {"STATE_LIGHTING", new MapEntry {RowType = typeof(StateLighting)}},
            {"STATES", new MapEntry {RowType = typeof(States), HasIndexBitRelations = true}},
            {"STATS", new MapEntry {RowType = typeof(Stats)}},
            {"STATS_FUNC", new MapEntry {FileName = "STATSFUNC", RowType = typeof(StatsFunc)}},
            {"STATS_SELECTOR", new MapEntry {FileName = "STATSSELECTOR", RowType = typeof(ExcelTables)}},
            {"STRING_FILES", new MapEntry {RowType = typeof(StringFiles)}},
            {"TASK_STATUS", new MapEntry {RowType = typeof(ExcelTables)}},
            {"TAG", new MapEntry {RowType = typeof(Tag)}},
            {"TASKS", new MapEntry {RowType = typeof(Tasks)}},
            {"TEXTURE_TYPES", new MapEntry {FileName = "TEXTURETYPES", RowType = typeof(TextureTypes)}},
            {"TREASURE", new MapEntry {RowType = typeof(Treasure)}},
            {"UI_COMPONENT", new MapEntry {RowType = typeof(UIComponent)}},
            {"UNIT_EVENT_TYPES", new MapEntry {FileName = "UNITEVENTS", RowType = typeof(UnitEvents)}},
            {"UNITMODE_GROUPS", new MapEntry {RowType = typeof(UnitModeGroups)}},
            {"UNITMODES", new MapEntry {RowType = typeof(UnitModes)}},
            {"UNITTYPES", new MapEntry {RowType = typeof(UnitTypes), HasIndexBitRelations = true}},
            {"WARDROBE_LAYER", new MapEntry {FileName = "WARDROBE", RowType = typeof(Wardrobe)}},
            {"WARDROBE_APPEARANCE_GROUP", new MapEntry {RowType = typeof(WardrobeAppearanceGroup)}},
            {"WARDROBE_BLENDOP", new MapEntry {RowType = typeof(WardrobeBlendOp)}},
            {"WARDROBE_BODY", new MapEntry {RowType = typeof(WardrobeBody)}},
            {"WARDROBE_LAYERSET", new MapEntry {RowType = typeof(WardrobeBlendOp)}},
            {"WARDROBE_MODEL", new MapEntry {RowType = typeof(WardrobeModel)}},
            {"WARDROBE_MODEL_GROUP", new MapEntry {RowType = typeof(WardrobeModelGroup)}},
            {"WARDROBE_PART", new MapEntry {RowType = typeof(WardrobePart)}},
            {"WARDROBE_TEXTURESET", new MapEntry {RowType = typeof(WardrobeTextureSet)}},
            {"WARDROBE_TEXTURESET_GROUP", new MapEntry {RowType = typeof(WardrobeTextureSetGroup)}},
            {"WEATHER", new MapEntry {RowType = typeof(Weather)}},
            {"WEATHER_SETS", new MapEntry {RowType = typeof(WeatherSets)}},

                
            // TCv4 - different
            {"_TCv4_ACHIEVEMENTS", new MapEntry {IsTCv4 = true, RowType = typeof(AchievementsTCv4)}},
            {"_TCv4_ACT", new MapEntry {IsTCv4 = true, RowType = typeof(ActTCv4)}},
            {"_TCv4_AFFIXES", new MapEntry {IsTCv4 = true, RowType = typeof(AffixesTCv4)}},
            {"_TCv4_BACKGROUNDSOUNDS2D", new MapEntry {IsTCv4 = true, RowType = typeof(BackGroundSounds2DTCv4)}},
            {"_TCv4_BADGE_REWARDS", new MapEntry {IsTCv4 = true, RowType = typeof(BadgeRewardsTCv4)}},
            {"_TCv4_CHARACTER_CLASS", new MapEntry {IsTCv4 = true, RowType = typeof(CharacterClassTCv4)}},
            {"_TCv4_DAMAGE_EFFECTS", new MapEntry {IsTCv4 = true, FileName = "DAMAGEEFFECTS", RowType = typeof(DamageEffectsTCv4)}},
            {"_TCv4_DAMAGETYPES", new MapEntry {IsTCv4 = true, RowType = typeof(DamageTypesTCv4)}},
            {"_TCv4_INVENTORY", new MapEntry {IsTCv4 = true, RowType = typeof(InventoryTCv4)}},
            {"_TCv4_ITEM_LOOKS", new MapEntry {IsTCv4 = true, RowType = typeof(ItemLooksTCv4)}},
            {"_TCv4_ITEM_QUALITY", new MapEntry {IsTCv4 = true, FileName = "ITEMQUALITY", RowType = typeof(ItemQualityTCv4)}},
            {"_TCv4_ITEMS", new MapEntry {IsTCv4 = true, RowType = typeof(ItemsTCv4)}},
            {"_TCv4_OBJECTS", new MapEntry {IsTCv4 = true, RowType = typeof(ItemsTCv4)}},
            {"_TCv4_MONSTERS", new MapEntry {IsTCv4 = true, RowType = typeof(ItemsTCv4)}},
            {"_TCv4_PLAYERS", new MapEntry {IsTCv4 = true, RowType = typeof(ItemsTCv4)}},
            {"_TCv4_MISSILES", new MapEntry {IsTCv4 = true, RowType = typeof(ItemsTCv4)}},
            {"_TCv4_MATERIALS_COLLISION", new MapEntry {IsTCv4 = true, RowType = typeof(MaterialsCollisionTCv4)}},
            {"_TCv4_LEVEL", new MapEntry {IsTCv4 = true, FileName = "LEVELS", RowType = typeof(LevelsTCv4)}},
            {"_TCv4_LEVEL_SCALING", new MapEntry {IsTCv4 = true, FileName = "LEVELSCALING", RowType = typeof(LevelScalingTCv4)}},
            {"_TCv4_ROOM_INDEX", new MapEntry {IsTCv4 = true, FileName = "LEVELS_ROOM_INDEX", RowType = typeof(LevelsRoomIndexTCv4)}},
            {"_TCv4_PLAYERLEVELS", new MapEntry {IsTCv4 = true, RowType = typeof(PlayerLevelsTCv4)}},
            {"_TCv4_PROPS", new MapEntry {IsTCv4 = true, RowType = typeof(LevelsRoomIndexTCv4)}},
            {"_TCv4_RECIPES", new MapEntry {IsTCv4 = true, RowType = typeof(RecipesTCv4)}},
            {"_TCv4_SKILLS", new MapEntry {IsTCv4 = true, RowType = typeof(SkillsTCv4)}},
            {"_TCv4_SKILLEVENTTYPES", new MapEntry {IsTCv4 = true, RowType = typeof(SkillEventTypesTCv4)}},
            {"_TCv4_SKILLTABS", new MapEntry {IsTCv4 = true, RowType = typeof(SkillTabsTCv4)}},
            {"_TCv4_SOUND_MIXSTATES", new MapEntry {IsTCv4 = true, FileName = "SOUNDMIXSTATES", RowType = typeof(SoundMixStatesTCv4)}},
            {"_TCv4_SOUNDS", new MapEntry {IsTCv4 = true, RowType = typeof(SoundsTCv4)}},
            {"_TCv4_STATS", new MapEntry {IsTCv4 = true, RowType = typeof(StatsTCv4)}},
            {"_TCv4_TREASURE", new MapEntry {IsTCv4 = true, RowType = typeof(TreasureTCv4)}},
            {"_TCv4_UNITMODE_GROUPS", new MapEntry {IsTCv4 = true, RowType = typeof(UnitModeGroupsTCv4)}},
            {"_TCv4_UNITMODES", new MapEntry {IsTCv4 = true, RowType = typeof(UnitModesTCv4)}},
            {"_TCv4_UNITTYPES", new MapEntry {IsTCv4 = true, RowType = typeof(UnitTypesTCv4), HasIndexBitRelations = true}},
            {"_TCv4_WARDROBE_LAYER", new MapEntry {IsTCv4 = true, FileName = "WARDROBE", RowType = typeof(WardrobeTCv4)}},


            //TCv4 - Same
            {"_TCv4_AFFIXTYPES", new MapEntry {IsTCv4 = true, RowType = typeof(AffixTypes)}},
            {"_TCv4_AI_BEHAVIOR", new MapEntry {IsTCv4 = true, RowType = typeof(AiBehaviour)}},
            {"_TCv4_AICOMMON_STATE", new MapEntry {IsTCv4 = true, RowType = typeof(AiCommonState)}},
            {"_TCv4_AI_INIT", new MapEntry {IsTCv4 = true, RowType = typeof(AiInit)}},
            {"_TCv4_AI_START", new MapEntry {IsTCv4 = true, RowType = typeof(AiStart)}},
            {"_TCv4_ANIMATION_CONDITION", new MapEntry {IsTCv4 = true, RowType = typeof(AnimationCondition)}},
            {"_TCv4_ANIMATION_GROUP", new MapEntry {IsTCv4 = true, FileName = "ANIMATION_GROUPS", RowType = typeof(AnimationGroups)}},
            {"_TCv4_ANIMATION_STANCE", new MapEntry {IsTCv4 = true, RowType = typeof(AnimationStance)}},
            {"_TCv4_BACKGROUNDSOUNDS", new MapEntry {IsTCv4 = true, RowType = typeof(BackGroundSounds)}},
            {"_TCv4_BACKGROUNDSOUNDS3D", new MapEntry {IsTCv4 = true, RowType = typeof(BackGroundSounds3D)}},
            {"_TCv4_BONES", new MapEntry {IsTCv4 = true, RowType = typeof(Bones)}},
            {"_TCv4_BONEWEIGHTS", new MapEntry {IsTCv4 = true, RowType = typeof(Bones)}},
            {"_TCv4_BOOKMARKS", new MapEntry {IsTCv4 = true, RowType = typeof(ExcelTables)}},
            {"_TCv4_BUDGETS_MODEL", new MapEntry {IsTCv4 = true, RowType = typeof(BudgetsModel)}},
            {"_TCv4_BUDGETS_TEXTURE_MIPS", new MapEntry {IsTCv4 = true, RowType = typeof(BudgetTextureMips)}},
            {"_TCv4_CHAT_INSTANCED_CHANNELS", new MapEntry {IsTCv4 = true, RowType = typeof(ChatInstancedChannels)}},
            {"_TCv4_COLORSETS", new MapEntry {IsTCv4 = true, RowType = typeof(ColorSets)}},
            {"_TCv4_CONDITION_FUNCTIONS", new MapEntry {IsTCv4 = true, RowType = typeof(ConditionFunctions)}},
            {"_TCv4_DIALOG", new MapEntry {IsTCv4 = true, RowType = typeof(Dialog)}},
            {"_TCv4_DIFFICULTY", new MapEntry {IsTCv4 = true, RowType = typeof(Difficulty)}},
            {"_TCv4_CHARDISPLAY", new MapEntry {IsTCv4 = true, FileName = "DISPLAY_CHAR", RowType = typeof(Display)}},
            {"_TCv4_ITEMDISPLAY", new MapEntry {IsTCv4 = true, FileName = "DISPLAY_ITEM", RowType = typeof(Display)}},
            {"_TCv4_EFFECTS_FILES", new MapEntry {IsTCv4 = true, RowType = typeof(EffectsFiles)}},
            {"_TCv4_EFFECTS", new MapEntry {IsTCv4 = true, FileName = "EFFECTS_INDEX", RowType = typeof(EffectsIndex)}},
            {"_TCv4_EFFECTS_SHADERS", new MapEntry {IsTCv4 = true, RowType = typeof(EffectsShaders)}},
            //{"_TCv4_EXCELTABLES", new MapEntry {IsTCv4 = true, RowType = typeof(ExcelTables)}},
            {"_TCv4_FACTION", new MapEntry {IsTCv4 = true, RowType = typeof(Faction)}},
            {"_TCv4_FACTION_STANDING", new MapEntry {IsTCv4 = true, RowType = typeof(FactionStanding)}},
            {"_TCv4_FILTER_CHATFILTER", new MapEntry {IsTCv4 = true, FileName = "CHATFILTER", RowType = typeof(Filter)}},
            {"_TCv4_FILTER_NAMEFILTER", new MapEntry {IsTCv4 = true, FileName = "NAMEFILTER", RowType = typeof(Filter)}},
            {"_TCv4_FONT", new MapEntry {IsTCv4 = true, RowType = typeof(Font)}},
            {"_TCv4_FONTCOLORS", new MapEntry {IsTCv4 = true, FileName = "FONTCOLOR", RowType = typeof(FontColor)}},
            {"_TCv4_FOOTSTEPS", new MapEntry {IsTCv4 = true, RowType = typeof(FootSteps)}},
            {"_TCv4_GAME_GLOBALS", new MapEntry {IsTCv4 = true, FileName = "GAMEGLOBALS", RowType = typeof(GameGlobals)}},
            //{"_TCv4_GLOBAL_INDEX", new MapEntry {IsTCv4 = true, FileName = "GLOBALINDEX", RowType = typeof(Global)}},
            {"_TCv4_GLOBAL_STRING", new MapEntry {IsTCv4 = true, FileName = "GLOBALSTRING", RowType = typeof(Global)}},
            {"_TCv4_GLOBAL_THEMES", new MapEntry {IsTCv4 = true, RowType = typeof(GlobalThemes)}},
            {"_TCv4_INITDB", new MapEntry {IsTCv4 = true, RowType = typeof(InitDb)}},
            {"_TCv4_INTERACT", new MapEntry {IsTCv4 = true, RowType = typeof(Interact)}},
            {"_TCv4_INTERACT_MENU", new MapEntry {IsTCv4 = true, RowType = typeof(InteractMenu)}},
            {"_TCv4_INVENTORY_TYPES", new MapEntry {IsTCv4 = true, RowType = typeof(InventoryTypes)}},
            {"_TCv4_INVLOC", new MapEntry {IsTCv4 = true, RowType = typeof(InvLoc)}},
            {"_TCv4_ITEM_LEVELS", new MapEntry {IsTCv4 = true, RowType = typeof(ItemLevels)}},
            {"_TCv4_ITEM_LOOK_GROUPS", new MapEntry {IsTCv4 = true, RowType = typeof(ItemLookGroups)}},
            {"_TCv4_LEVEL_DRLG_CHOICE", new MapEntry {IsTCv4 = true, FileName = "LEVELS_DRLG_CHOICE", RowType = typeof(LevelsDrlgChoice)}},
            {"_TCv4_LEVEL_DRLGS", new MapEntry {IsTCv4 = true, FileName = "LEVELS_DRLGS", RowType = typeof(LevelsDrlgs)}},
            {"_TCv4_LEVEL_FILE_PATHS", new MapEntry {IsTCv4 = true, FileName = "LEVELS_FILE_PATH", RowType = typeof(LevelsFilePath)}},
            {"_TCv4_LEVEL_ENVIRONMENTS", new MapEntry {IsTCv4 = true, FileName = "LEVELS_ENV", RowType = typeof(LevelsEnv)}},
            {"_TCv4_LEVEL_RULES", new MapEntry {IsTCv4 = true, FileName = "LEVELS_RULES", RowType = typeof(LevelsRules)}},
            {"_TCv4_LEVEL_THEMES", new MapEntry {IsTCv4 = true, FileName = "LEVELS_THEMES", RowType = typeof(LevelsThemes)}},
            {"_TCv4_LOADING_TIPS", new MapEntry {IsTCv4 = true, RowType = typeof(LoadingTips)}},
            {"_TCv4_MATERIALS_GLOBAL", new MapEntry {IsTCv4 = true, RowType = typeof(MaterialsGlobal)}},
            {"_TCv4_MELEEWEAPONS", new MapEntry {IsTCv4 = true, RowType = typeof(MeleeWeapons)}},
            {"_TCv4_MONLEVEL", new MapEntry {IsTCv4 = true, RowType = typeof(MonLevel)}},
            {"_TCv4_MONSCALING", new MapEntry {IsTCv4 = true, RowType = typeof(MonScaling)}},
            {"_TCv4_MONSTER_NAME_TYPES", new MapEntry {IsTCv4 = true, RowType = typeof(MonsterNameTypes)}},
            {"_TCv4_MONSTER_NAMES", new MapEntry {IsTCv4 = true, RowType = typeof(MonsterNames)}},
            {"_TCv4_MONSTER_QUALITY", new MapEntry {IsTCv4 = true, RowType = typeof(MonsterQuality)}},
            {"_TCv4_MOVIE_SUBTITLES", new MapEntry {IsTCv4 = true, RowType = typeof(MovieSubTitles)}},
            {"_TCv4_MOVIELISTS", new MapEntry {IsTCv4 = true, RowType = typeof(MovieLists)}},
            {"_TCv4_MOVIES", new MapEntry {IsTCv4 = true, RowType = typeof(Movies)}},
            {"_TCv4_MUSIC", new MapEntry {IsTCv4 = true, RowType = typeof(Music)}},
            {"_TCv4_MUSICCONDITIONS", new MapEntry {IsTCv4 = true, RowType = typeof(MusicConditions)}},
            {"_TCv4_MUSICGROOVELEVELS", new MapEntry {IsTCv4 = true, RowType = typeof(MusicGrooveLevels)}},
            {"_TCv4_MUSICGROOVELEVELTYPES", new MapEntry {IsTCv4 = true, RowType = typeof(MusicGrooveLevelTypes)}},
            {"_TCv4_MUSIC_REF", new MapEntry {IsTCv4 = true, FileName = "MUSICREF", RowType = typeof(MusicRef)}},
            {"_TCv4_MUSIC_SCRIPT_DEBUG", new MapEntry {IsTCv4 = true, FileName = "MUSICSCRIPTDEBUG", RowType = typeof(MusicScriptDebug)}},
            {"_TCv4_MUSICSTINGERS", new MapEntry {IsTCv4 = true, RowType = typeof(MusicStingers)}},
            {"_TCv4_MUSICSTINGERSETS", new MapEntry {IsTCv4 = true, RowType = typeof(MusicStingerSets)}},
            {"_TCv4_NPC", new MapEntry {IsTCv4 = true, RowType = typeof(Npc)}},
            {"_TCv4_OBJECTTRIGGERS", new MapEntry {IsTCv4 = true, RowType = typeof(ObjectTriggers)}},
            {"_TCv4_OFFER", new MapEntry {IsTCv4 = true, RowType = typeof(Offer)}},
            {"_TCv4_PALETTES", new MapEntry {IsTCv4 = true, RowType = typeof(Palettes)}},
            {"_TCv4_PETLEVEL", new MapEntry {IsTCv4 = true, RowType = typeof(MonLevel)}},
            {"_TCv4_PLAYER_RACE", new MapEntry {IsTCv4 = true, FileName = "PLAYERRACE", RowType = typeof(PlayerRace)}},
            {"_TCv4_PROPERTIES", new MapEntry {IsTCv4 = true, RowType = typeof(Properties), HasScriptTable = true}},
            {"_TCv4_PROCS", new MapEntry {IsTCv4 = true, RowType = typeof(Procs)}},
            {"_TCv4_QUEST", new MapEntry {IsTCv4 = true, RowType = typeof(Quest)}},
            {"_TCv4_QUEST_CAST", new MapEntry {IsTCv4 = true, RowType = typeof(QuestCast)}},
            {"_TCv4_QUEST_STATE", new MapEntry {IsTCv4 = true, RowType = typeof(QuestState)}},
            {"_TCv4_QUEST_STATE_VALUE", new MapEntry {IsTCv4 = true, RowType = typeof(ExcelTables)}},
            {"_TCv4_QUEST_STATUS", new MapEntry {IsTCv4 = true, RowType = typeof(QuestStatus)}},
            {"_TCv4_QUEST_TEMPLATE", new MapEntry {IsTCv4 = true, RowType = typeof(QuestTemplate)}},
            {"_TCv4_RARENAMES", new MapEntry {IsTCv4 = true, RowType = typeof(RareNames)}},
            {"_TCv4_RECIPELISTS", new MapEntry {IsTCv4 = true, RowType = typeof(RecipeLists)}},
            {"_TCv4_SKILLGROUPS", new MapEntry {IsTCv4 = true, RowType = typeof(SkillGroups)}},
            {"_TCv4_SKU", new MapEntry {IsTCv4 = true, RowType = typeof(Sku)}},
            {"_TCv4_SOUNDBUSES", new MapEntry {IsTCv4 = true, RowType = typeof(SoundBuses)}},
            {"_TCv4_SOUND_MIXSTATE_VALUES", new MapEntry {IsTCv4 = true, FileName = "SOUNDMIXSTATEVALUES", RowType = typeof(SoundMixStateValues)}},
            {"_TCv4_SOUNDVCAS", new MapEntry {IsTCv4 = true, RowType = typeof(SoundVidCas)}},
            {"_TCv4_SOUNDVCASETS", new MapEntry {IsTCv4 = true, RowType = typeof(SoundVideoCasets)}},
            {"_TCv4_SPAWN_CLASS", new MapEntry {IsTCv4 = true, FileName = "SPAWNCLASS", RowType = typeof(SpawnClass)}},
            {"_TCv4_SUBLEVEL", new MapEntry {IsTCv4 = true, RowType = typeof(SubLevel)}},
            {"_TCv4_STATE_EVENT_TYPES", new MapEntry {IsTCv4 = true, RowType = typeof(StateEventTypes)}},
            {"_TCv4_STATE_LIGHTING", new MapEntry {IsTCv4 = true, RowType = typeof(StateLighting)}},
            {"_TCv4_STATES", new MapEntry {IsTCv4 = true, RowType = typeof(States), HasIndexBitRelations = true}},
            {"_TCv4_STATS_FUNC", new MapEntry {IsTCv4 = true, FileName = "STATSFUNC", RowType = typeof(StatsFunc)}},
            {"_TCv4_STATS_SELECTOR", new MapEntry {IsTCv4 = true, FileName = "STATSSELECTOR", RowType = typeof(ExcelTables)}},
            //{"_TCv4_STRING_FILES", new MapEntry {IsTCv4 = true, RowType = typeof(StringFiles)}},
            {"_TCv4_TASK_STATUS", new MapEntry {IsTCv4 = true, RowType = typeof(ExcelTables)}},
            {"_TCv4_TAG", new MapEntry {IsTCv4 = true, RowType = typeof(Tag)}},
            {"_TCv4_TASKS", new MapEntry {IsTCv4 = true, RowType = typeof(Tasks)}},
            {"_TCv4_TEXTURE_TYPES", new MapEntry {IsTCv4 = true, FileName = "TEXTURETYPES", RowType = typeof(TextureTypes)}},
            //{"_TCv4_UI_COMPONENT", new MapEntry {IsTCv4 = true, RowType = typeof(UIComponent)}},
            {"_TCv4_UNIT_EVENT_TYPES", new MapEntry {IsTCv4 = true, FileName = "UNITEVENTS", RowType = typeof(UnitEvents)}},
            {"_TCv4_WARDROBE_APPEARANCE_GROUP", new MapEntry {IsTCv4 = true, RowType = typeof(WardrobeAppearanceGroup)}},
            {"_TCv4_WARDROBE_BLENDOP", new MapEntry {IsTCv4 = true, RowType = typeof(WardrobeBlendOp)}},
            {"_TCv4_WARDROBE_BODY", new MapEntry {IsTCv4 = true, RowType = typeof(WardrobeBody)}},
            {"_TCv4_WARDROBE_LAYERSET", new MapEntry {IsTCv4 = true, RowType = typeof(WardrobeBlendOp)}},
            {"_TCv4_WARDROBE_MODEL", new MapEntry {IsTCv4 = true, RowType = typeof(WardrobeModel)}},
            {"_TCv4_WARDROBE_MODEL_GROUP", new MapEntry {IsTCv4 = true, RowType = typeof(WardrobeModelGroup)}},
            {"_TCv4_WARDROBE_PART", new MapEntry {IsTCv4 = true, RowType = typeof(WardrobePart)}},
            {"_TCv4_WARDROBE_TEXTURESET", new MapEntry {IsTCv4 = true, RowType = typeof(WardrobeTextureSet)}},
            {"_TCv4_WARDROBE_TEXTURESET_GROUP", new MapEntry {IsTCv4 = true, RowType = typeof(WardrobeTextureSetGroup)}},
            {"_TCv4_WEATHER", new MapEntry {IsTCv4 = true, RowType = typeof(Weather)}},
            {"_TCv4_WEATHER_SETS", new MapEntry {IsTCv4 = true, RowType = typeof(WeatherSets)}},


            // Empty Excel files
            {"GOSSIP", new MapEntry {IsEmpty = true}},
            {"INVLOCIDX", new MapEntry {IsEmpty = true}},
            {"SOUNDOVERRIDES", new MapEntry {IsEmpty = true}},


            // Non-Indexed Excel file
            {"LANGUAGE", new MapEntry {ManualLoad = true, RowType = typeof(Language)}},
            {"REGION", new MapEntry {ManualLoad = true, RowType = typeof(Region)}},


            // Mythos Excel files
            {"LEVEL_AREAS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_ADJ_BRIGHT", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_ADJECTIVES", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_AFFIXS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_CANYON_NOUNS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_CAVE_NOUNS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_DESERTGOTHIC_NOUNS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_GOBLIN_NAMES", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_GOBLIN_NOUNS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_GOTHIC_NOUNS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_FARMLAND_NOUNS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_FOREST_NOUNS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_HEATH_NOUNS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_LINKER", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_MADLIB", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_PROPERNAMEZONE1", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_PROPERNAMEZONE2", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_TEMPLE_NOUNS", new MapEntry {IsMythos = true}},
            {"LEVEL_AREAS_SUFFIXS", new MapEntry {IsMythos = true}},
            {"LEVEL_ZONES", new MapEntry {IsMythos = true}},
            {"QUEST_COUNT_TUGBOAT", new MapEntry {IsMythos = true}},
            {"QUEST_DICTIONARY_FOR_TUGBOAT", new MapEntry {IsMythos = true}},
            {"QUEST_RANDOM_FOR_TUGBOAT", new MapEntry {IsMythos = true}},
            {"QUEST_RANDOM_TASKS_FOR_TUGBOAT", new MapEntry {IsMythos = true}},
            {"QUEST_REWARD_BY_LEVEL_TUGBOAT", new MapEntry {IsMythos = true}},
            {"QUEST_TITLES_FOR_TUGBOAT", new MapEntry {IsMythos = true}},
            {"QUESTS_TASKS_FOR_TUGBOAT", new MapEntry {IsMythos = true}},

            // I think these are Mythos
            {"ACHIEVEMENT_SLOTS", new MapEntry {IsMythos = true}},
            {"CRAFTING_SLOTS", new MapEntry {IsMythos = true}},
            {"DEBUG_BARS", new MapEntry {IsMythos = true}},
            {"RENDER_FLAGS", new MapEntry {IsMythos = true}},
            {"SKILL_LEVELS", new MapEntry {IsMythos = true}},
            {"SKILL_STATS", new MapEntry {IsMythos = true}},

            // Strings files
            {"Strings_Affix", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Cinematic", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Common", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Credits", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_DisplayFormat", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Install", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Items", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Level", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_LoadingTips", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Monsters", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Names", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Quest", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Skills", new MapEntry {RowType = typeof(StringsFile)}},
            {"Strings_Strings", new MapEntry {RowType = typeof(StringsFile)}},

            // Empty Strings files
            {"Strings_Install_MSI", new MapEntry {IsEmpty = true}}
        };
    }
}